url: "https://remobi.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/ubiq2" # the subpath of your site, e.g. /blog
title: "Ubqtours" # the name of your site, e.g. ACME Corp.
